In [1]:
import torch
#DO NOT CHANGE THE SEED
torch.manual_seed(2)

x = torch.randint(low=0,high=256,size=(1,150))
### YOUR CODE STARTS HERE ###
print(x.shape)
u=x.view(10,5,3)
x_resize = x.view(10,5,3)
print(x_resize.shape)
# Step2: Generate a gaussian random tensor (mean =0, variance=1) of shape (5,3) and store it in variable y1 \\
# # Use torch.randn()
# # y1=torch.randn(5,3)
# print(y1.mean())
# print(y1.var())
# print(y1)
y1 = torch.randn(5,3)
print(y1.shape)
# Generate a uniform random tensor (interval [-10,10)) of shape (5,3) and store it in variable y2

# Use torch.rand()
y2 = torch.rand(5,3)*20-10
print(y2.shape)
print(y2)
# Perform elementwise multiplication between x_resize and y1, store it in variable mul_output1
mul_output1 = torch.mul(x_resize,y1)
print(mul_output1.shape)
#fetch the last dimention element of the tensor
final_output1,_ = torch.max(mul_output1,dim=2)
#print the max value of final_output1
print(final_output1)


mul_output2 = torch.mul(x_resize,y2)

final_output2,_ = torch.max(mul_output2,dim=2)

# ### YOUR CODE ENDS HERE ###

print(torch.mean(final_output1+final_output2))

torch.Size([1, 150])
torch.Size([10, 5, 3])
torch.Size([5, 3])
torch.Size([5, 3])
tensor([[ 4.0043,  2.7128, -9.3933],
        [-5.8302, -3.5366,  3.6749],
        [ 8.9350,  4.4561,  3.7776],
        [-8.4856,  6.4707,  3.5814],
        [-3.2156, -4.7981,  2.8429]])
torch.Size([10, 5, 3])
tensor([[147.3205,  -5.1863,  42.8768,  -0.6713, 264.2102],
        [ 41.2147, -34.8894,  21.1526,  -5.2551,  74.4928],
        [ 90.3215, -11.7445,  38.3033,  -8.4393, 261.7293],
        [106.1059, -12.2584,  28.5846, -11.9671, 316.3080],
        [152.5820, -13.1742, 135.4908, -23.6877, 174.0486],
        [ 64.0143, -39.1483,  47.4504,  -4.1238,  94.6824],
        [222.7346, -12.1004, 130.9173,  -8.2475, 160.0146],
        [ 59.6297, -21.7095, 130.9173, -14.0016, 104.4292],
        [ 45.5992, -51.3912, 128.0588, -10.4474, 274.1335],
        [182.3969, -38.8970,  81.7518,  -4.9388, 296.4612]])
tensor(879.7391)


In [2]:
import torch
import torch.nn as nn


#DO NOT CHANGE THE SEED
torch.manual_seed(0)

y_true = torch.tensor([0.3, 0.7, 0.6])
print(y_true.shape)
print(y_true)
m, n = 3, 2
M = torch.randn(m, n, requires_grad=True)
print(M.shape)
print(M)
v = torch.randn(n, requires_grad=True)
print(v.shape)
print(v)
#calculate the matrix vector product between M and v and store it in y_pred
y_pred = torch.matmul(M,v)
print(y_pred.shape)
print(y_pred)
### YOUR CODE STARTS HERE ###
# y_pred = ___
### YOUR CODE ENDS HERE ###

torch.Size([3])
tensor([0.3000, 0.7000, 0.6000])
torch.Size([3, 2])
tensor([[ 1.5410, -0.2934],
        [-2.1788,  0.5684],
        [-1.0845, -1.3986]], requires_grad=True)
torch.Size([2])
tensor([0.4033, 0.8380], requires_grad=True)
torch.Size([3])
tensor([ 0.3757, -0.4024, -1.6095], grad_fn=<MvBackward0>)


In [3]:
# Next, implement a custom loss function in PyTorch that computes the mean squared error (MSE) 
# between two tensors (y_true, y_pred), but only for elements where the target tensor y_true is greater than 0.5. Save the calculated MSE loss in a variable named "loss".

# *(Hint: First create a mask on y_true and then multiply the mask with the loss)*


torch.manual_seed(0)
class CustomMSELoss(nn.Module):
    def __init__(self):
        super(CustomMSELoss,self).__init__()
    def forward(self, y_pred, y_true):
        mask=y_true>0.5
        print(mask)
        squared_diff = (y_pred-y_true)**2
        masked_squared_diff = squared_diff[mask]
        # For calculating the mean, take the sum of masked_squared_diff and divide by 3.
        loss = torch.sum(masked_squared_diff)/3
        return loss
    

loss_fn = CustomMSELoss()
loss = loss_fn(y_pred, y_true)
print(loss)  



tensor([False,  True,  True])
tensor(2.0324, grad_fn=<DivBackward0>)


In [5]:
### DO NOT CHANGE ###
# Compute gradients using autograd
loss.backward(retain_graph=True)  # This computes gradients for all tensors that have requires_grad=True

### YOUR CODE STARTS HERE ###
grad_M = torch.autograd.grad(loss, M, retain_graph=True)[0]
grad_v = torch.autograd.grad(loss, v, retain_graph=True)[0]
### YOUR CODE ENDS HERE ###

print("Sum of Gradient Means: ", grad_M.mean()+grad_v.mean())

Sum of Gradient Means:  tensor(1.9638)


In [1]:
import torch
import torch.nn as nn

# DO NOT CHANGE THE SEED
torch.manual_seed(0)

y_true = torch.tensor([0.3, 0.7, 0.6])
print(y_true.shape)
print(y_true)
m, n = 3, 2
M = torch.randn(m, n, requires_grad=True)
print(M.shape)
print(M)
v = torch.randn(n, requires_grad=True)
print(v.shape)
print(v)

# Calculate the matrix-vector product between M and v and store it in y_pred
y_pred = torch.matmul(M, v)
print(y_pred.shape)
print(y_pred)

# Define a custom MSE loss function
class CustomMSELoss(nn.Module):
    def __init__(self):
        super(CustomMSELoss, self).__init__()
    
    def forward(self, y_pred, y_true):
        mask = y_true > 0.5
        squared_diff = (y_pred - y_true) ** 2
        masked_squared_diff = squared_diff[mask]
        # Use mask.sum() to get the number of valid elements for the mean calculation
        loss = torch.sum(masked_squared_diff) / mask.sum()
        return loss

loss_fn = CustomMSELoss()
loss = loss_fn(y_pred, y_true)
print(loss)

# Compute gradients using autograd
loss.backward()  # This computes gradients for all tensors that have requires_grad=True

# Calculate gradients with respect to M and v
grad_M = torch.autograd.grad(loss, M, retain_graph=True)[0]
grad_v = torch.autograd.grad(loss, v, retain_graph=True)[0]

print("Sum of Gradient Means: ", grad_M.mean() + grad_v.mean())


torch.Size([3])
tensor([0.3000, 0.7000, 0.6000])
torch.Size([3, 2])
tensor([[ 1.5410, -0.2934],
        [-2.1788,  0.5684],
        [-1.0845, -1.3986]], requires_grad=True)
torch.Size([2])
tensor([0.4033, 0.8380], requires_grad=True)
torch.Size([3])
tensor([ 0.3757, -0.4024, -1.6095], grad_fn=<MvBackward0>)
tensor(3.0486, grad_fn=<DivBackward0>)


RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.